#ifndef POKDEFS_H
#define POKDEFS_H
#include <pokibot/lib/pokutils.h>

#define BOARD_MIN_X    -1500.0f
#define BOARD_MAX_X    1500.0f
#define BOARD_SIZE_X   (BOARD_MAX_X - BOARD_MIN_X)
#define BOARD_CENTER_X ((BOARD_MIN_X + BOARD_MAX_X) / 2.0f)
#define BOARD_MIN_Y    0.0f
#define BOARD_MAX_Y    2000.0f
#define BOARD_SIZE_Y   (BOARD_MAX_Y - BOARD_MIN_Y)
#define BOARD_CENTER_Y ((BOARD_MIN_Y + BOARD_MAX_Y) / 2.0f)

#define ROBOT_RADIUS                 180.0f
#define ROBOT_DIST_TO_FLAT_SIZE      165.0f
#define ROBOT_CENTER_POLE_RADIUS     49.0f

#define ROBOT_CALIB_SIDE_OFFSET      (-M_PI / 2)
// #define ROBOT_PUSH_SIDE_OFFSET      (M_PI - M_PI / 6)

#define OPPONENT_ROBOT_MAX_RADIUS   191.0f // 1.2/(2*pi)

#define TAG_POLE_MIN_RADIUS (70.0f/2.0f)

#define DISTANCE_FROM_OBSTACLE_MARGIN  200.0f
#define LIDAR_STOP_DISTANCE_MAX (ROBOT_RADIUS + OPPONENT_ROBOT_MAX_RADIUS - TAG_POLE_MIN_RADIUS + DISTANCE_FROM_OBSTACLE_MARGIN)
#define LIDAR_STOP_DISTANCE_MIN (ROBOT_RADIUS + 2.0f)
#define LIDAR_STOP_ANGLE_START    (((float)M_PI)/4.0f)
#define LIDAR_STOP_ANGLE_END      ((float)M_PI)

#endif
